# Generated by Django 4.1 on 2024-08-13 22:33

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.emotion')),
            ],
        ),
        migrations.AddIndex(
            model_name='emotion',
            index=django.contrib.postgres.indexes.HashIndex(fields=['name'], name='main_emotio_name_6b48bb_hash'),
        ),
        migrations.AddIndex(
            model_name='emotionrecord',
            index=models.Index(fields=['created_at'], name='main_emotio_created_cba382_idx'),
        ),
    ]
