# Generated by Django 5.1 on 2024-08-14 00:28

from django.db import migrations


def create_emotion_types(apps, schema_editor):
    Emotion = apps.get_model('main', 'Emotion')
    Emotion.objects.create(name='Anger')
    Emotion.objects.create(name='Contempt')
    Emotion.objects.create(name='Disgust')
    Emotion.objects.create(name='Fear')
    Emotion.objects.create(name='Happy')
    Emotion.objects.create(name='Neutral')
    Emotion.objects.create(name='Sad')
    Emotion.objects.create(name='Surprise')


def delete_emotion_types(apps, schema_editor):
    Emotion = apps.get_model('main', 'Emotion')
    Emotion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_emotion_types, delete_emotion_types),
    ]
